name: Code Inspector

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: pnpm install

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: Build
    env:
      NODE_ENV: development
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm test

  lint:
    needs: build
    runs-on: ubuntu-latest
    environment: Build
    env:
      NODE_ENV: development
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm lint

  typecheck:
    needs: build
    runs-on: ubuntu-latest
    environment: Build
    env:
      NODE_ENV: development
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm typecheck
